
export const tweetConstants = {
    LOAD_TWEETS_SUCCESS: "LOAD_TWEETS_SUCCESS",
    LOAD_TWEETS_FAIL: "LOAD_TWEETS_FAIL",
    TWEETS_SEARCH_SUCCESS: "LOAD_TWEETS_SEARCH_SUCCESS",
    TWEETS_SEARCH_FAIL: "TWEETS_SEARCH_FAIL",
    CLEAR_TWEETS: "CLEAR_TWEETS"
}
